# do run with variable mask length
accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 2 --mask_length_max 128 --vary_mask_percent --run_name "bin16_mask_diff"
# redo runs with bad results
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 4 --run_name "bin64_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 64 --run_name "bin16_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 32 --run_name "bin64_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 32 --run_name "bin512_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 128 --run_name "bin512_mask128"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 128 --run_name "bin1024_mask128"
# we do a grid search over bin size and mask length
# - bin sizes: 16, 32, 64, 128, 512, 1024
# - mask lengths: 1, 2, 4, 8, 16, 32, 64, 128
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 4 --run_name "bin64_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 8 --run_name "bin64_mask8"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 16 --run_name "bin64_mask16"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 32 --run_name "bin64_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 4 --run_name "bin128_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 8 --run_name "bin128_mask8"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 16 --run_name "bin128_mask16"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 32 --run_name "bin128_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 8 --run_name "bin512_mask8"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 16 --run_name "bin512_mask16"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 8 --run_name "bin32_mask8"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 16 --run_name "bin32_mask16"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 1 --run_name "bin16_mask1"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 2 --run_name "bin16_mask2"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 4 --run_name "bin16_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 8 --run_name "bin16_mask8"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 16 --run_name "bin16_mask16"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 32 --run_name "bin16_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 64 --run_name "bin16_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 16 --mask_length 128 --run_name "bin16_mask128"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 1 --run_name "bin32_mask1"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 2 --run_name "bin32_mask2"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 4 --run_name "bin32_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 32 --run_name "bin32_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 64 --run_name "bin32_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 32 --mask_length 128 --run_name "bin32_mask128"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 1 --run_name "bin64_mask1"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 2 --run_name "bin64_mask2"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 64 --run_name "bin64_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 64 --mask_length 128 --run_name "bin64_mask128"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 1 --run_name "bin128_mask1"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 2 --run_name "bin128_mask2"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 64 --run_name "bin128_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 128 --mask_length 128 --run_name "bin128_mask128"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 1 --run_name "bin512_mask1"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 2 --run_name "bin512_mask2"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 4 --run_name "bin512_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 32 --run_name "bin512_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 64 --run_name "bin512_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 512 --mask_length 128 --run_name "bin512_mask128"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 1 --run_name "bin1024_mask1"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 2 --run_name "bin1024_mask2"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 4 --run_name "bin1024_mask4"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 8 --run_name "bin1024_mask8"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 16 --run_name "bin1024_mask16"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 32 --run_name "bin1024_mask32"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 64 --run_name "bin1024_mask64"
# accelerate launch scripts/train.py configs/default.yml --bin_size 1024 --mask_length 128 --run_name "bin1024_mask128"