batch_size: 32
checkpoint_path: checkpoints
dataset: cdminix/libritts-aligned
do_save: true
eval_every_n_steps: 1000
eval_only: false
gradient_clip_val: 10.0
hub_repo: null
log_every_n_steps: 100
lr: 0.0005
lr_schedule: linear_with_warmup
lr_warmup_steps: 100
n_epochs: 1
n_steps: 10000
n_workers: 16
output_path: outputs
push_to_hub: false
run_name: bin16_mask2
save_every_n_steps: 1000
save_onnx: false
seed: 0
train_split: train
val_split: dev[:25%]
wandb_dir: wandb
wandb_mode: online
wandb_project: masked-prosody-modeling
