lr: 5.0e-4
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 1000
n_steps: 10000
n_layers: 16
hidden_dim: 512
n_workers: 96
val_split: "dev[:25%]"
wandb_project: "masked-prosody-modeling-v2"
overwrite: False
name: "algo"
do_save: True
save_every_n_steps: 5000
eval_every_n_steps: 1000