lr: 5.0e-4
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 100
n_steps: 10000
n_layers: 16
hidden_dim: 512
n_workers: 96
val_split: "dev[:25%]"
wandb_project: "masked-prosody-modeling"
wandb_mode: "offline"
overwrite: False
name: "algo"
do_save: False
save_every_n_steps: 5000