lr: 5.0e-4
lr_schedule: "linear_with_warmup"
lr_warmup_steps: 1000
n_layers: 16
hidden_dim: 512
n_workers: 16
val_split: "dev[:25%]"
wandb_project: "masked-prosody-modeling"
wandb_mode: "online"
do_save: True